package main

import (
	"fmt"
	"strings"
)

func commandSetAbility(cfg *config, args[]string) error{
	if len(args) < 2{
		return fmt.Errorf("Not enough arguments given.")
	}
	monName := args[0]
	mon, ok := cfg.Pokedex[monName]
	if !ok {
		return fmt.Errorf("You have not caught %v", monName)
	}
	ability := strings.Join(args[1:], "-")
	if !IsValid(ability){
		return fmt.Errorf("Please enter a valid ability name")
	}
	mon.Ability = ability
	cfg.Pokedex[monName] = mon
	_, ok = cfg.Party[monName]
	if ok {
		cfg.Party[monName] = mon
	}
	return nil
}


var set map[string]struct{}

func init() {
	set = make(map[string]struct{}, len(Abilities)*2)
	for _, name := range Abilities {
		// Store canonical and lowercase for case-insensitive lookups
		set[name] = struct{}{}
		set[strings.ToLower(name)] = struct{}{}
	}
}

// IsValid reports whether the provided ability name matches a known ability.
// Matching is case-insensitive and ignores leading/trailing whitespace.
func IsValid(name string) bool {
	if name == "" {
		return false
	}
	name = strings.Trim(name, "-")
	if _, ok := set[name]; ok {
		return true
	}
	_, ok := set[strings.ToLower(name)]
	return ok
}

var Abilities = []string{
	"Adaptability",
	"Aerilate",
	"Aftermath",
	"Air-Lock",
	"Analytic",
	"Anger-Point",
	"Anger-Shell",
	"Anticipation",
	"Arena-Trap",
	"Armor-Tail",
	"Aroma-Veil",
	"As-One",
	"Aura-Break",
	"Bad-Dreams",
	"Ball-Fetch",
	"Battery",
	"Battle-Armor",
	"Battle-Bond",
	"Beads-of-Ruin",
	"Beast-Boost",
	"Berserk",
	"Big-Pecks",
	"Blaze",
	"Bulletproof",
	"Cacophony",
	"Cheek-Pouch",
	"Chilling-Neigh",
	"Chlorophyll",
	"Clear-Body",
	"Cloud-Nine",
	"Color-Change",
	"Comatose",
	"Commander",
	"Competitive",
	"Compound-Eyes",
	"Contrary",
	"Corrosion",
	"Costar",
	"Cotton-Down",
	"Cud-Chew",
	"Curious-Medicine",
	"Cursed-Body",
	"Cute-Charm",
	"Damp",
	"Dancer",
	"Dark-Aura",
	"Dauntless-Shield",
	"Dazzling",
	"Defeatist",
	"Defiant",
	"Delta-Stream",
	"Desolate-Land",
	"Disguise",
	"Download",
	"Dragon's-Maw",
	"Drizzle",
	"Drought",
	"Dry-Skin",
	"Early-Bird",
	"Earth-Eater",
	"Effect-Spore",
	"Electric-Surge",
	"Electromorphosis",
	"Embody-Aspect",
	"Emergency-Exit",
	"Fairy-Aura",
	"Filter",
	"Flame-Body",
	"Flare-Boost",
	"Flash-Fire",
	"Flower-Gift",
	"Flower-Veil",
	"Fluffy",
	"Forecast",
	"Forewarn",
	"Friend-Guard",
	"Frisk",
	"Full-Metal-Body",
	"Fur-Coat",
	"Gale-Wings",
	"Galvanize",
	"Gluttony",
	"Good-as-Gold",
	"Gooey",
	"Gorilla-Tactics",
	"Grass-Pelt",
	"Grassy-Surge",
	"Grim-Neigh",
	"Guard-Dog",
	"Gulp-Missile",
	"Guts",
	"Hadron-Engine",
	"Harvest",
	"Healer",
	"Heatproof",
	"Heavy-Metal",
	"Honey-Gather",
	"Hospitality",
	"Huge-Power",
	"Hunger-Switch",
	"Hustle",
	"Hydration",
	"Hyper-Cutter",
	"Ice-Body",
	"Ice-Face",
	"Ice-Scales",
	"Illuminate",
	"Illusion",
	"Immunity",
	"Imposter",
	"Infiltrator",
	"Innards-Out",
	"Inner-Focus",
	"Insomnia",
	"Intimidate",
	"Intrepid-Sword",
	"Iron-Barbs",
	"Iron-Fist",
	"Justified",
	"Keen-Eye",
	"Klutz",
	"Leaf-Guard",
	"Levitate",
	"Libero",
	"Light-Metal",
	"Lightning-Rod",
	"Limber",
	"Lingering-Aroma",
	"Liquid-Ooze",
	"Liquid-Voice",
	"Long-Reach",
	"Magic-Bounce",
	"Magic-Guard",
	"Magician",
	"Magma-Armor",
	"Magnet-Pull",
	"Marvel-Scale",
	"Mega-Launcher",
	"Merciless",
	"Mimicry",
	"Mind's-Eye",
	"Minus",
	"Mirror-Armor",
	"Misty-Surge",
	"Mold-Breaker",
	"Moody",
	"Motor-Drive",
	"Moxie",
	"Multiscale",
	"Multitype",
	"Mummy",
	"Mycelium-Might",
	"Natural-Cure",
	"Neuroforce",
	"Neutralizing-Gas",
	"No-Guard",
	"Normalize",
	"Oblivious",
	"Opportunist",
	"Orichalcum-Pulse",
	"Overcoat",
	"Overgrow",
	"Own-Tempo",
	"Parental-Bond",
	"Pastel-Veil",
	"Perish-Body",
	"Pickpocket",
	"Pickup",
	"Pixilate",
	"Plus",
	"Poison-Heal",
	"Poison-Point",
	"Poison-Puppeteer",
	"Poison-Touch",
	"Power-Construct",
	"Power-of-Alchemy",
	"Power-Spot",
	"Prankster",
	"Pressure",
	"Primordial-Sea",
	"Prism-Armor",
	"Propeller-Tail",
	"Protean",
	"Protosynthesis",
	"Psychic-Surge",
	"Punk-Rock",
	"Pure-Power",
	"Purifying-Salt",
	"Quark-Drive",
	"Queenly-Majesty",
	"Quick-Draw",
	"Quick-Feet",
	"Rain-Dish",
	"Rattled",
	"Receiver",
	"Reckless",
	"Refrigerate",
	"Regenerator",
	"Ripen",
	"Rivalry",
	"RKS-System",
	"Rock-Head",
	"Rocky-Payload",
	"Rough-Skin",
	"Run-Away",
	"Sand-Force",
	"Sand-Rush",
	"Sand-Spit",
	"Sand-Stream",
	"Sand-Veil",
	"Sap-Sipper",
	"Schooling",
	"Scrappy",
	"Screen-Cleaner",
	"Seed-Sower",
	"Serene-Grace",
	"Shadow-Shield",
	"Shadow-Tag",
	"Sharpness",
	"Shed-Skin",
	"Sheer-Force",
	"Shell-Armor",
	"Shield-Dust",
	"Shields-Down",
	"Simple",
	"Skill-Link",
	"Slow-Start",
	"Slush-Rush",
	"Sniper",
	"Snow-Cloak",
	"Snow-Warning",
	"Solar-Power",
	"Solid-Rock",
	"Soul-Heart",
	"Soundproof",
	"Speed-Boost",
	"Stakeout",
	"Stall",
	"Stalwart",
	"Stamina",
	"Stance-Change",
	"Static",
	"Steadfast",
	"Steam-Engine",
	"Steelworker",
	"Steely-Spirit",
	"Stench",
	"Sticky-Hold",
	"Storm-Drain",
	"Strong-Jaw",
	"Sturdy",
	"Suction-Cups",
	"Super-Luck",
	"Supersweet-Syrup",
	"Supreme-Overlord",
	"Surge-Surfer",
	"Swarm",
	"Sweet-Veil",
	"Swift-Swim",
	"Sword-of-Ruin",
	"Symbiosis",
	"Synchronize",
	"Tablets-of-Ruin",
	"Tangled-Feet",
	"Tangling-Hair",
	"Technician",
	"Telepathy",
	"Tera-Shell",
	"Tera-Shift",
	"Teraform-Zero",
	"Teravolt",
	"Thermal-Exchange",
	"Thick-Fat",
	"Tinted-Lens",
	"Torrent",
	"Tough-Claws",
	"Toxic-Boost",
	"Toxic-Chain",
	"Toxic-Debris",
	"Trace",
	"Transistor",
	"Triage",
	"Truant",
	"Turboblaze",
	"Unaware",
	"Unburden",
	"Unnerve",
	"Unseen-Fist",
	"Vessel-of-Ruin",
	"Victory-Star",
	"Vital-Spirit",
	"Volt-Absorb",
	"Wandering-Spirit",
	"Water-Absorb",
	"Water-Bubble",
	"Water-Compaction",
	"Water-Veil",
	"Weak-Armor",
	"Well-Baked-Body",
	"White-Smoke",
	"Wimp-Out",
	"Wind-Power",
	"Wind-Rider",
	"Wonder-Guard",
	"Wonder-Skin",
	"Zen-Mode",
	"Zero-to-Hero",
}
